"""Analysis findings produced by the rule engine."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class Severity(StrEnum):
    """Supported finding severity levels."""

    PASS = "PASS"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


@dataclass(frozen=True, slots=True)
class Finding:
    """A single result generated by an analysis rule."""

    severity: Severity
    title: str
    message: str
    recommendation: str = ""
